services:
    db:
      image:  mysql:9.0
      command: --local-infile=1
      ports:
        - "8081:8081"
      restart: always
      environment:
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
        - MYSQL_DATABASE=test
        - MYSQL_ROOT_PASSWORD=hard_pass
      volumes:
        - ./source_database/data:/var/lib/mysql
        - ./source_database/init.sql:/docker-entrypoint-initdb.d/init.sql

    adminer:
      image: adminer
      ports:
        - "8080:8080"
      environment:
        ADMINER_DEFAULT_SERVER: db
      depends_on:
        - db


volumes:
  source_database:
    driver: local
