basePath: /
definitions:
  domain.ErrorMessage:
    properties:
      description:
        type: string
      header:
        type: string
    type: object
  domain.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  domain.LoginResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      roleId:
        type: integer
    type: object
  domain.User:
    properties:
      active:
        type: boolean
      birthDate:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      officeID:
        type: integer
      password:
        type: string
      roleID:
        description: Office    Office //`gorm:"column:OfficeID;foreignKey:ID"`
        type: integer
    type: object
  domain.UserId:
    properties:
      id:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Описание работы сервера
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Login of user
      tags:
      - Login
  /users:
    get:
      consumes:
      - application/json
      description: get employees
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: List of employee users
      tags:
      - User
  /users/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Create of user
      tags:
      - User
  /users/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: scheme of user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.UserId'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Delete of user
      tags:
      - User
  /users/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: scheme of user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Update of user
      tags:
      - User
swagger: "2.0"
